apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUzTWpNek1qTTFOakFlRncweE9URXdNamt3TmpVNU1UWmFGdzB5T1RFd01qWXdOalU1TVRaYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUzTWpNek1qTTFOakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkR6aDFoa20vT3RSQkJ0eXVLTkhWNlFva3E5L1Y0U1lJbjZKOHlpelNwdGgKVjVSYjlKNDFZMFV4QlFqNVM0V3B1TnNPWVJEYUV6UFpFQ2xlbk9PVzlqR2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFENkZad0t0UER6CnVESzdsRXd4OWxjaktTaVNCdXVqUy84b2NKRmJzZmFMdGdJZ09ZTnRsakRzK2VtcWd6M2dpckV3ZThYUVpYSlUKOGV0S0szOHNrZXAzQTBFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 86b5f82bb2f2e8f2ac152a262819638b
    username: admin
